name: Deploy to Netlify on pull requests

on: [push, workflow_dispatch]

env:
  node_version: 14.x

jobs:
  environment:
    name: ğŸŒ± Load Environment
    runs-on: ubuntu-latest

    steps:
      - name: âš™ï¸ Node.js version used - ${{ env.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

  test:
    name: ğŸ§ª Test
    runs-on: ubuntu-latest
    needs: environment

    steps:
      - uses: actions/checkout@v2

      - name: ğŸ”§ Installation of dependencies
        run: yarn run install-test-dependencies && yarn install --frozen-lockfile

      - name: ğŸ§ª Test CI
        run: yarn run test-ci

      - name: ğŸ§ª Lint CI
        run: yarn run lint-ci

      - name: ğŸ“¦ Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: '${{ runner.os }} - Lint Report'
          path: ./lintReport.json

  build:
    runs-on: ubuntu-latest
    needs: [environment, test]

    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      - name: Prepare
        run: yarn install --frozen-lockfile

      - name: Install Netlify
        run: yarn add netlify-cli

      # We use the "no-sapling" build so the 50 MB parameters file isn't downloaded
      - name: Build site
        run: yarn run build:no-sapling

      # Deploy the site with netlify-cli
      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=www --alias=$GITHUB_SHA --message=$GITHUB_SHA
